.TH "md__c_h_a_n_g_e_l_o_g" 3 "Sat Sep 5 2020" "Version 1.3.0" "uspm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_h_a_n_g_e_l_o_g \- Changelog 
All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fCKeep a Changelog\fP, and this project adheres to \fCSemantic Versioning\fP\&.
.SH "[Unreleased]"
.PP
.SH "Added"
.PP
.IP "\(bu" 2
Documentation
.IP "\(bu" 2
\fCcheck_if_first_run()\fP checks if the current run is the first one by checking for the main files\&.
.IP "\(bu" 2
Checksums
.IP "\(bu" 2
\fCuspm-chksum\fP can get the checksum of a file and also compare 2 files by checksum
.PP
.SH "Changed"
.PP
.IP "\(bu" 2
Made uspp a shared library instead of static
.IP "\(bu" 2
\fCuspm-mkpkg\fP is now ran outside of the package directory
.IP "\(bu" 2
Split up the different software into their own folders to meet with uspm packaging plans
.IP "\(bu" 2
\fCcheck_dependencies_and_install()\fP is now \fCcheck_for_dependencies()\fP
.IP "\(bu" 2
Moved \fCuspm\fP -> \fCuspm-main\fP and \fClibuspp/uspm\&.{c,h}\fP -> \fClibuspp/uspp\&.{c,h}\fP
.PP
.SH "Removed"
.PP
.IP "\(bu" 2
Unnecessary print statements
.IP "\(bu" 2
\fCinstall_dep_file()\fP
.PP
.SH "[1\&.2\&.1] - 2020-08-3"
.PP
.SH "Changed"
.PP
.IP "\(bu" 2
Made it so both the clang and the GCC version are given\&.
.PP
.SH "[1\&.2\&.0] - 2020-08-31"
.PP
.SH "Added"
.PP
.IP "\(bu" 2
The USPP library
.IP "  \(bu" 4
a library that is used for USPM and USPM-extended to work
.IP "  \(bu" 4
replaces the source and header files that were a part of USPM
.PP

.PP
.SH "Changed"
.PP
.IP "\(bu" 2
Moved all the excess source and header files to the new USPP library
.PP
.SH "Removed"
.PP
.IP "\(bu" 2
The 'check dependencies' function because its very useless
.PP
.SH "[1\&.1\&.1] - 2020-02-23"
.PP
.SS "Fixed"
.IP "\(bu" 2
Fixed uspm-extended where commands weren't doing what they were supposed to do
.PP
.SH "[1\&.1\&.0] - 2020-02-20"
.PP
.SS "Added"
.IP "\(bu" 2
Travis CI build configuration
.IP "\(bu" 2
Manpage
.IP "\(bu" 2
Ability to install/uninstall/check more than one package
.IP "\(bu" 2
\fCuspm-mkpkg\fP tool that makes package creation easier
.IP "\(bu" 2
Build status to README
.IP "\(bu" 2
Extended commands
.IP "\(bu" 2
Added proper version checking for dependencies
.PP
.SS "Changed"
.IP "\(bu" 2
Changed the default configuration's mirror site\&.
.IP "\(bu" 2
Changed \fCCMakeLists\&.txt\fP file to include \fCuspm-mkpkg\fP
.IP "\(bu" 2
Changed location of \fCuspm\fP C source and header files
.IP "\(bu" 2
Changed package creation instructions within the README
.IP "\(bu" 2
Dependency resolution now is seperate from normal install functions\&.
.PP
.SS "Fixed"
.IP "\(bu" 2
Fixed bug where default mirror links to a nonexistent server
.PP
.SH "[1\&.0\&.1] - 2020-02-04"
.PP
.SS "Added"
.IP "\(bu" 2
Option to use CMake instead of Makefile
.PP
.SS "Changed"
.IP "\(bu" 2
Removed 'C Edition' from README
.IP "\(bu" 2
Added install instructions for CMake
.PP
.SS "Fixed"
.IP "\(bu" 2
Fixed bug where if config file doesn't exist, it breaks\&.
.PP
.SH "[1\&.0\&.0] - 2020-02-03"
.PP
.SS "Added"
.IP "\(bu" 2
Install, Uninstall, Check dependencies commands 
.PP

