.TH "md_docs_03-_typical__repository__structure" 3 "Sat Sep 5 2020" "Version 1.3.0" "uspm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_03-_typical__repository__structure \- Typical Repository Structure 
\fI\fBREQUIRED:\fP\fP \fCpackages\&.json\fP - houses package names and their checksums
.PP
package\&.json 
.PP
.nf
{
    "uspm":"9c19a317129b8c42ff9358f809beef01", 
    "cjson":"97771ff98b30d382bc1917a8089d2e11"
}

.fi
.PP
.PP
The rest are basically just \&.uspm packages that you'd want on the server\&. 
.PP
.nf
\&.
+-- cjson\&.uspm
+-- libcurl\&.uspm
+-- openssl\&.uspm
+-- packages\&.json
+-- tar-tbc\&.uspm
+-- uspm\&.uspm
+-- uspp-src\&.uspm

.fi
.PP
.PP
If you'd like you can keep archived versions of packages in the \fCarchive\fP folder\&. However, the USPM standard does not require that such a folder exist\&. 
