.TH "md_docs_02-_typical__u_s_p_m__file" 3 "Sat Sep 5 2020" "Version 1.3.0" "uspm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_02-_typical__u_s_p_m__file \- The typical USPM File 

.PP
.nf
\&.
+-- PACKAGECODE
+-- PACKAGEDATA
+-- files
|   +-- usr
|       +-- bin
|   +-- etc
|       +-- program_custom_config_file

.fi
.PP
 
