.TH "md_docs_01-_types_of__u_s_p_m__packages" 3 "Sat Sep 5 2020" "Version 1.3.0" "uspm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_01-_types_of__u_s_p_m__packages \- Types of USPM packages 
\fCpackagename\&.uspm\fP - This is the typical package name\&. It will always be precompiled binaries\&.
.PP
\fCpackagename-src\&.uspm\fP - This is a package that is grabbed from source\&. There are 2 general types accepted:
.IP "1." 4
An almost empty structure with a command to pull from a git repo within the \fCPACKAGECODE\fP file or
.IP "2." 4
A package with the default \fCPACKAGECODE\fP file and just the source files hosted within the package\&.
.PP
.PP
\fCpackagename-tbc\&.uspm\fP - A mix between the two above, contains the source files within, but also has its install script be to compile and install the software\&. Very useful when there are a lot of different files and programs going everywhere or if you have a need to give the user ample time to configure certain headers or configurations beforehand\&. 
